# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install -g @aeternity/aeproject
      - run: npm install
      - run: aeproject env
      - run: aeproject test
      - run: |
          npm run generate-bytecode-aci-hashes
          git diff --exit-code
